tryber/sd-013-b-project-recipes-app

package-lock.json
src/App.js
src/component/Header.js
src/component/IconButton.js

Requisito 9 finalizado com sucesso

[Group - 14] Requisito 9

---

package-lock.json
src/App.js
src/context/Provider.js
src/context/RecipesContext.js
src/index.js
src/pages/Login.jsx

https://trello.com/c/BqT5JET0/2-2-crie-todos-os-elementos-que-devem-respeitar-os-atributos-descritos-no-prot%C3%B3tipo-para-a-tela-de-login

Requirement 02

---

src/App.js
src/components/Button.jsx
src/components/Input.jsx
src/pages/Comidas.jsx
src/pages/Login.jsx
src/redux/actions/index.js
src/routes.js

Requisitos do 1 ao 8 feitos em pair programming

Requisitos 1 ao 8 pairprograming

---

README.md
package-lock.json
src/App.js
src/Context/RecipesContext.js
src/Context/RecipesProvider.jsx
src/Pages/Login.js
src/Pages/MainFoodPage.jsx
src/Pages/PerfilPage.jsx

[Main group 7] Header

---

README.md
package-lock.json
src/App.js
src/Context/RecipesContext.js
src/Context/RecipesProvider.jsx
src/Pages/Login.js
src/Pages/MainFoodPage.jsx

[Main group 7] Login Page

---

src/App.js
src/mini-components/Button.js
src/pages/ExploreDrinkPage.js
src/pages/ExploreFoodPage.js
src/pages/ExplorePage.js

Requisito 67, 68 e 69 finalizados com sucesso

[Group/14] - Requisito 67, 68 e 69

---

src/Redux/Actions/index.js
src/Redux/Reducer/login.js
src/pages/Login.jsx

https://trello.com/b/9nCMU6bX/gp-4-trybe-app-de-receitas
- Email sendo salvo no redux
- Input de email e password
- Por enquanto sem css

[Group 4] Tela de login

---

src/App.css
src/App.js
src/components/Footer.jsx
src/index.js
src/pages/ExploreIngredients.jsx
src/pages/Explorer.jsx
src/pages/ExplorerCountries.jsx
src/pages/ExplorerDrinksOrFoods.jsx
src/pages/FavoriteRecipes.jsx
src/pages/FavoritesRecipes.jsx
src/pages/Home.jsx
src/pages/Login.jsx
src/pages/Perfil.jsx
src/pages/RecipeDetails.jsx
src/pages/RecipesDetails.jsx
src/pages/RecipesInProgress.jsx
src/pages/RecipesMade.jsx

Foram adicionados os requisitos 19 e 20, bem como o setup inicial de rotas da aplicação.

[Grupo 19] Requisitos 19 e 20

---

README.md
package-lock.json
package.json
src/App.js
src/App.test.js
src/pages/Login.jsx
src/tests/App.test.js
src/tests/Login.test.js
src/tests/renderWithRouter.js
src/utils/LoginContext.js
src/utils/LoginProvider.js

Trello Card Requirement 2: https://trello.com/c/Dxj7PYRa/2-2-crie-todos-os-elementos-que-devem-respeitar-os-atributos-descritos-no-prot%C3%B3tipo-para-a-tela-de-login
Trello Card Requirement 3: https://trello.com/c/8hT7Oboc/3-3-desenvolva-a-tela-de-maneira-que-a-pessoa-deve-conseguir-escrever-seu-email-no-input-de-email
Trello Card Requirement 4: https://trello.com/c/Jy43YsJ4/4-4-desenvolva-a-tela-de-maneira-que-a-pessoa-deve-conseguir-escrever-sua-senha-no-input-de-senha
Trello Card Requirement 5: https://trello.com/c/UBqgbWOR/5-5-desenvolva-a-tela-de-maneira-que-o-formul%C3%A1rio-s%C3%B3-seja-v%C3%A1lido-ap%C3%B3s-um-email-v%C3%A1lido-e-uma-senha-de-mais-de-6-caracteres-serem-pr

[Group 23] Requiremets 2 to 5

---

src/components/Header.jsx
src/pages/Comidas.jsx
src/redux/actions/index.js
src/redux/reducers/index.js
src/redux/reducers/reducerHeader.js

Adicionando funcionalidades ao componente header, para completar os requisitos do header, é necessário implementá-lo às outras páginas, o valor do input search está sendo salvo no store global, reducerHeader

Header group 21

---

src/components/RecipesCardDrink.jsx
src/components/RecipesCardFood.jsx
src/pages/Drinks.jsx
src/pages/Foods.jsx

Reverts tryber/sd-013-b-project-recipes-app#194

Revert "[Main group 2] Search bar parte2"

---

src/components/CardsComida.jsx
src/components/CardsDrinks.jsx
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/services/fetchRadioBebidas.js
src/services/fetchRadioComidas.js

Adicionando requisitos do 13 ao 18! VQV

Requisitos 13 ao 18 rafaelromano group 21

---

src/tests/Header.test.js

Main group 27 header tests

---

src/components/RecipesCardDrink.jsx
src/components/RecipesCardFood.jsx
src/components/SearchBar.jsx
src/context/RecipesProvider.js
src/pages/Drinks.jsx
src/pages/DrinksDetails.jsx
src/pages/Foods.jsx
src/pages/FoodsDetails.jsx
src/services/FetchApiAll.js
src/services/FetchApiDrinks.js
src/services/FetchApiFoods.js

refatora implementação que renderiza os cards

[main-group-2] -Tela-req25

---

src/pages/Bebidas.jsx
src/pages/Comidas.jsx

Arrumando requisitos16

---

src/App.js
src/components/Card.jsx
src/components/CardList.jsx
src/pages/Home.jsx
src/pages/Perfil.jsx
src/services/data.js

Commit com a estrutura do fetch da pagina home. Falta concluir a estrutura dos cards renderizados com o resultado da api.

[Grupo 19] Services

---

cypress/integration/header_spec.js
src/App.js
src/Header/Header.test.js
src/Header/HeaderContex.js
src/Header/Index.js
src/Header/style.css
src/Services/renderWithRouter.js
src/index.js

[Link trello](https://trello.com/c/tqwGqWln)

[Criando header] Requisito 9-11-12

---

src/App.js
src/pages/NotFound.jsx
src/pages/index.js

Not Found Page 

---

src/components/Button.jsx
src/components/Input.jsx
src/components/RecipesCardDrink.jsx
src/components/RecipesCardFood.jsx
src/context/RecipesProvider.js
src/pages/Login.jsx
src/pages/Profile.jsx
src/services/FetchApiAll.js

[Main group 2] Refatora Componentes e implementa Persistência do State

[Main group 2] Refatora Componentes e Implementa Persistência do "State" 

---

src/App.js
src/component/Header.js
src/context/Provider.js
src/index.js
src/mini-components/IconButton.js
src/pages/DoneRecipes.js
src/pages/DrinkDetails.js
src/pages/Drinks.js
src/pages/Explore.js
src/pages/ExploreDrinks.js
src/pages/ExploreDrinksByIngredients.js
src/pages/ExploreFoods.js
src/pages/ExploreFoodsByArea.js
src/pages/ExploreFoodsByIngredients.js
src/pages/FavoriteRecipes.js
src/pages/FoodDetails.js
src/pages/Foods.js
src/pages/InProcessDrink.js
src/pages/InProcessFood.js
src/pages/Login.js
src/pages/Profile.js

Requisitos 10, 11 e 12 finalizados com sucesso

[Group 14] Requisito 10, 11 e 12

---

src/App.js
src/components/Header.js
src/components/SearchBar.js
src/components/SearchHeader.js
src/context/RecipesContext.js
src/context/RecipesProvider.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Detalhes-bebidas.js
src/pages/Detalhes-comidas.js
src/pages/Explorar.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js
src/pages/ExplorarIngredientes.js
src/pages/Perfil.js
src/pages/ReceitasFavoritas.js
src/pages/ReceitasFeitas.js
src/services/DrinkApi.js
src/services/MealApi.js

13 - https://trello.com/c/9ZKXKdbU/13-13-implemente-os-elementos-da-barra-de-busca-respeitando-os-atributos-descritos-no-prot%C3%B3tipo
14 - https://trello.com/c/8bx38A59/14-14-posicione-a-barra-logo-abaixo-do-header-e-implemente-3-radio-buttons-ingrediente-nome-e-primeira-letra
15 - https://trello.com/c/O0YneKU6/15-15-busque-na-api-de-comidas-caso-a-pessoa-esteja-na-p%C3%A1gina-de-comidas-e-na-de-bebidas-caso-esteja-na-de-bebidas
16 - https://trello.com/c/VB3saAOr/16-16-redirecione-para-a-tela-de-detalhes-da-receita-caso-apenas-uma-receita-seja-encontrada-com-o-id-da-mesma-na-url
17 - https://trello.com/c/C33t20sb/17-17-mostre-as-receitas-em-cards-caso-mais-de-uma-receita-seja-encontrada
18 - https://trello.com/c/WHO5DPQy/18-18-exiba-um-alert-caso-nenhuma-receita-seja-encontrada

[Group 3] - SearchHeader Req 13 ao 18

---

cypress/integration/recipe_detail_spec.js
src/pages/DrinkDetails/index.js
src/pages/DrinkDetails/style.css
src/pages/MealDetails/index.js
src/pages/MealDetails/style.css

[Grupo 24] Tela detalhes

---

src/components/Button.jsx
src/components/ExploreDrinkFood.jsx
src/pages/ExploreDrinks.jsx
src/pages/ExploreFoods.jsx
src/services/FetchApiAll.js

[Main group 2] - Implementa Tela de Explorar Bebidas ou Comidas

[Main group 2] - Implementa Tela de Explorar Bebidas ou Comidas

---

src/components/ButtonExplorer.jsx
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarComidas.jsx
src/services/fetchRadioBebidas.js
src/services/fetchRadioComidas.js
src/tests/ExplorarBebidas.test.js
src/tests/ExplorarComidas.test.js

Finalizada a tela para explorar bebidas ou comidas:
- Requisitos do 70 ao 74;
- Passou nos testes locais de linter e do cypress;
- Entregue com os testes unitários cobrindo 100% das funcionalidades.

[GRUPO 21] Tela de explorar bebidas ou comidas

---

src/component/DoneRecipeCards.js
src/component/FavoriteRecipeCards.js
src/context/Provider.js
src/mini-components/IconButton.js
src/pages/DoneRecipes.js
src/pages/FavoriteRecipes.js
src/pages/Login.js

Requisitos 60 ao 66 finalizados com sucesso

[Group 14] Requisito 60, 61, 62, 63, 64, 65 e 66

---

src/component/DoneRecipeCards.js
src/context/Provider.js
src/mini-components/IconButton.js
src/pages/DoneRecipes.js
src/pages/Login.js

Requisitos 54 ao 59 finalizados com sucesso

[Group 14] Requisito 54, 55, 56, 57, 58 e 59

---

src/components/ButtonExplorer.jsx
src/pages/DetalhesBebidas.jsx
src/pages/DetalhesComidas.jsx
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarComidas.jsx
src/pages/ReceitasFavoritas.jsx
src/services/fetchRadioBebidas.js
src/services/fetchRadioComidas.js
src/services/functionsForDetails.js
src/tests/ExplorarBebidas.test.js
src/tests/ExplorarComidas.test.js

Foram corrigidos algumas lógicas da tela de detalhes de comidas/bebidas e acrescentado e implementada a tela de receitas favoritas! Trello atualizado.

Favorite recipes req 60 ao 66 rafael romano

---

src/Redux/actions/index.js
src/Redux/reducers/index.js
src/Redux/reducers/radioFilters.js
src/Redux/reducers/serchText.js
src/components/Header.jsx
src/components/SearchBar.jsx
src/pages/Home.jsx
src/pages/Perfil.jsx

Corrigi o requisito 11 que estava quebrando no teste e refatorei a página Home e o Redux.
Como estamos usando o Redux no projeto, talvez seja interessante cortar os 'useState' e criar reducers para 'foods' e 'drinks', o que acham?

[Main group 19]  Requisito 11 e Refatoração 

---

src/App.css
src/App.js
src/Context/RecipesProvider.jsx
src/Pages/DrinksPage.jsx
src/Pages/ExploreDrinksByIngredient.jsx
src/Pages/HeaderWithSearch.jsx
src/Pages/Utils/CategoriesButtons.jsx
src/Pages/Utils/InputSearchCocktails.jsx
src/Pages/Utils/InputSearchMeals.jsx

Main group 7 recipelist2

---

src/pages/Login.js

Requisito 7 nãos estava passando voltei como estava para passar o requisito 7

Requisito 7

---

src/pages/Bebidas.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js

Req 70 - https://trello.com/c/v1F76qJI/70-70-implemente-os-elementos-da-tela-de-explorar-bebidas-ou-comidas-respeitando-os-atributos-descritos-no-prot%C3%B3tipo
Req 71 - https://trello.com/c/RbJaofHF/71-71-desenvolva-3-bot%C3%B5es-um-para-explorar-por-ingrediente-um-para-explorar-por-local-de-origem-e-um-para-pegar-uma-receita-aleat%C3%B3r
Req 72 - https://trello.com/c/m8gGT0jZ/72-72-redirecione-a-pessoa-usu%C3%A1ria-ao-clicar-em-por-ingredientes-para-a-tela-de-explorar-por-ingredientes
Req 73 - https://trello.com/c/WVoRHRvV/73-73-redirecione-a-pessoa-usu%C3%A1ria-ao-clicar-em-por-local-de-origem-a-rota-deve-mudar-para-tela-de-explorar-por-local-de-origem
Req 74 - https://trello.com/c/gUQGYAqD/74-74-redirecione-a-pessoa-usu%C3%A1ria-ao-clicar-em-me-surpreenda-a-rota-deve-mudar-para-a-tela- …

[Group 3] - Explore drink meals reqs 70 71 72 73 74

---

src/component/Cards.js
src/component/SearchBar.js
src/context/Provider.js
src/pages/Drinks.js
src/pages/Foods.js

Requisito 13-14 s2 Mi

---

src/App.css
src/Pages/DrinkDetailsPage.jsx
src/Pages/FoodDetailsPage.jsx
src/components/DrinksSuggestions.jsx
src/components/Footer.jsx
src/components/MealsSuggestions.jsx
src/services/drinksAPI.js
src/services/foodAPI.js

finalize up to req39

---

src/Pages/ExploreMealsByArea.jsx

[Main Group 7] Explore By Area 

---

src/App.js
src/pages/ExploreDrinksArea.jsx
src/pages/ExploreDrinksIngredients.jsx
src/pages/ExploreFoodsArea.jsx
src/pages/ExploreFoodsIngredients.jsx
src/services/FetchApiAll.js

Implementações das tela de explorar por ingredientes e tela de explorar por área

[Main group 2] Explore Foods Ingredients/Area

---

src/components/DoneCard.jsx
src/components/DoneRecipesFilters.jsx
src/pages/ReceitasFeitas.jsx

Cards 
https://trello.com/c/jGctNw5l/54-54-implemente-os-elementos-da-tela-de-receitas-feitas-respeitando-os-atributos-descritos-no-prot%C3%B3tipo
https://trello.com/c/CgbPgwWt/55-55-desenvolva-a-tela-de-maneira-que-caso-a-receita-do-card-seja-uma-comida-ela-deve-possuir-a-foto-da-receita-o-nome-a-categoria
https://trello.com/c/JSc9pWVY/56-56-desenvolva-a-tela-de-maneira-que-caso-a-receita-do-card-seja-uma-bebida-ela-deve-possuir-a-foto-da-receita-o-nome-se-%C3%A9-alco%C3%B3l
https://trello.com/c/04so8hJX/57-57-desenvolva-a-solu%C3%A7%C3%A3o-de-maneira-que-o-bot%C3%A3o-de-compartilhar-deve-copiar-a-url-da-tela-de-detalhes-da-receita-para-o-clipboard
https://trello.com/c/Vl5O4TLQ/58-58-implemente-2-bot%C3%B5es-que-filtram-as-receitas-por-comida-ou-bebida-e-um-terceiro-que-remove-todos-os-fi …

[Group 13] Done Recipes

---

src/component/DoneRecipeCards.js
src/component/DrinkCardSpace.js
src/component/DrinkCards.js
src/component/DrinkCategoryButtons.js
src/component/DrinkCategorySpace.js
src/component/FavoriteRecipeCards.js
src/component/FoodCardSpace.js
src/component/FoodCards.js
src/component/FoodCategoryButtons.js
src/component/FoodCategorySpace.js
src/component/SearchBar.js
src/context/Provider.js
src/pages/DoneRecipes.js
src/pages/DrinkCategoryButtons.js
src/pages/DrinkCategorySpace.js
src/pages/Drinks.js
src/pages/FavoriteRecipes.js
src/pages/Foods.js

Requisito 25, 26 finalizados. Iniciando o requisito 27

[Group 14] Requisito 25

---

src/App.js
src/Pages/DrinkDetailsPage.jsx
src/Pages/FoodDetailsPage.jsx
src/Pages/RecipeInProgress.jsx
src/components/DrinksSuggestions.jsx

finalie req41 req42

---

src/components/RecipeDetails.js
src/context/Provider.js
src/helpers/getFoodOrDrinkProperties.js
src/helpers/handleFavorite.js

Tela de detalhes quase pronta.
Req 40 feito mas não passa no teste
Req 46 Hard Coded
Lint OK

[GRUPO 11] - Tela de detalhes

---

src/components/RenderCardSearch.jsx
src/components/SearchInput.js
src/context/Provider.js
src/context/recipesContext.js
src/pages/DetailsRecipe.js
src/pages/DrinkRecipes.js
src/pages/ExploreDrink.js
src/pages/ExploreFood.js
src/pages/FoodRecipes.js
src/pages/Login.js
src/pages/Recipes.js
src/services/index.js

Fiz algumas mudancas no codigo e adicionei alguns comentarios para melhorar a legibilidade.

Main group 9 refatoracao

---

package-lock.json
package.json
src/Pages/DrinkDetailsPage.jsx
src/Pages/FoodDetailsPage.jsx

finalize req43
npm install  '''npm install clipboard-copy''' otherwise test will not work =)

finalize req43

---

package-lock.json
package.json
src/pages/Explore.jsx

[Group 20] Jose Breno projeto app receita 67,68,69 2°

---

cypress/integration/recipe_detail_spec.js
src/Pages/DrinkDetailsPage.jsx
src/Pages/FoodDetailsPage.jsx
src/components/IngredientsList.jsx

Main group 27 ex44

---

cypress/integration/header_search_bar_spec.js
cypress/integration/header_spec.js
src/App.js
src/pages/Explorar-B-localdeOrigem.js
src/pages/Explorar-C-localdeOrigem.js

78 - https://trello.com/c/RnHlgYEK/78-78-implemente-os-elementos-da-tela-de-explorar-por-local-de-origem-respeitando-os-atributos-descritos-no-prot%C3%B3tipo
79 - https://trello.com/c/kITcVofF/79-79-desenvolva-as-mesmas-especifica%C3%A7%C3%B5es-da-tela-de-receitas-principal-com-a-diferen%C3%A7a-de-que-os-filtros-de-categoria-s%C3%A3o-substitu
80 - https://trello.com/c/8c8LVUUt/80-80-implemente-o-dropdown-de-maneira-que-devem-estar-dispon%C3%ADveis-todas-as-%C3%A1reas-retornadas-da-api-incluindo-a-op%C3%A7%C3%A3o-all-que-retor
81 - https://trello.com/c/SbhPAPZS/81-81-implemente-a-rota-que-deve-ser-apenas-explorar-comidas-%C3%A1rea

[Group 3] - Explorar por local de origem

---

src/pages/Comidas.jsx

Alguém tinha quebrado o req...
Está corrigido.
Favor rodarem os testes dos requisitos que já foram concluídos antes de subir PR pra verificar se não quebrou algo que estava pronto.

[Main group 19] correção req 14, 15 e 16

---

src/App.css
src/App.js
src/Pages/CustomCarousel.jsx
src/Pages/DrinkDetails.jsx
src/Pages/ExploreDrinksRecipesByIngredient.jsx
src/Pages/MealDetails.jsx
src/Pages/MealsInProgress.jsx
src/Pages/Utils/CategoriesButtons.jsx

Requisitos de Pagina de Detalhes

[Main Group 7] Página de Detalhes

---

src/App.js

Correção dos requisitos 22, 23 e 24.
O <Footer /> estava sendo renderizado duas vezes pq ele existia tanto nos componentes quanto no App.js.
Apaguei ele do App.js e corrigi os requisitos supracitados.

[Main group 19] req 22 23 24

---

src/App.js
src/Redux/Actions/filteredFoodsAction.js
src/Redux/Reducer/filteredFoods.js
src/Redux/Reducer/index.js
src/components/DrinkCards.jsx
src/components/FoodCards.jsx
src/components/Header.css
src/components/Header.jsx
src/components/HeaderWithSearch.jsx
src/components/HeaderWithSearchDrink.jsx
src/components/HeaderWithSearchFood.jsx
src/components/SearchBar.css
src/components/SearchBar.jsx
src/components/SearchBarDrink.jsx
src/components/SearchBarFood.jsx
src/pages/DoneRecipes.jsx
src/pages/Drink.jsx
src/pages/DrinkInProgress.jsx
src/pages/Explore.jsx
src/pages/ExploreDrink.jsx
src/pages/ExploreDrinkByIngredient.jsx
src/pages/ExploreFood.jsx
src/pages/ExploreFoodByIngredient.jsx
src/pages/ExploreFoodByOrigin.jsx
src/pages/FavoriteRecipes.jsx
src/pages/Food.jsx
src/pages/FoodInProgress.jsx
src/pages/Profile.jsx

[Main group 4] - Header & SearchBar

---

src/App.js
src/components/DrinkCards.jsx
src/components/FoodCards.jsx
src/components/Footer.jsx
src/components/SearchBarDrink.jsx
src/components/SearchBarFood.jsx
src/pages/DrinkDetails.jsx
src/pages/Explore.jsx
src/pages/ExploreDrink.jsx
src/pages/ExploreFood.jsx
src/pages/FoodDetails.jsx
src/pages/Login.jsx
src/pages/Profile.jsx
src/pages/RecipeDetails.css

Prontos até a parte de vídeo, falta a parte de recomendações, ainda não terminei, não façam merge agora.
https://www.figma.com/file/WatDxtKl7g54QxhDi9qdbq/App-Receitas?node-id=0%3A1
https://trello.com/b/9nCMU6bX/gp-4-trybe-app-de-receitas

[Group 4] [Food and Drink Details] 

---

src/pages/FavoritesRecipes.jsx

[Main group 2] Recipes Favorites req-66

[Main group 2] Recipes Favorites req-66

---

src/pages/DrinkDetails.jsx
src/pages/FoodDetails.jsx

Parte que falta para iniciar a tela de progresso

[Group 4] details

---

src/css/App.css
src/css/CardsRecomendations.css
src/css/Detalhes.css
src/css/ReceitasFavoritas.css
src/pages/DetalhesBebidas.jsx
src/pages/DetalhesComidas.jsx
src/pages/ReceitasFavoritas.jsx

Css detalhes favoritos
